### ISSUE TITLE
jsonblob: test misbehaves on some filesystems

### ISSUE THREAD

**Issue by hdonnay** [quay/claircore#1313]
```
 --- FAIL: TestStore (0.01s)
    jsonblob_test.go:27: open /tmp: operation not supported
    jsonblob_test.go:29: ref: 00000000-0000-0000-0000-000000000000
    jsonblob_test.go:35: wrote:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x432d98]

goroutine 36 [running]:
github.com/quay/claircore/libvuln/jsonblob.TestRoundtrip.func3()
	/go/pkg/mod/github.com/quay/claircore@v1.5.26/libvuln/jsonblob/jsonblob_test.go:78 +0x188
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/go/pkg/mod/golang.org/x/sync@v0.7.0/errgroup/errgroup.go:78 +0x58
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 34
	/go/pkg/mod/golang.org/x/sync@v0.7.0/errgroup/errgroup.go:75 +0x98
FAIL	github.com/quay/claircore/libvuln/jsonblob	0.390s
```

**Comment by hdonnay** [comment]
Ah, got too clever with the `diskbuf` bits.
