### ISSUE TITLE
RHEL dockerfile parser can panic parsing env vars

### ISSUE THREAD

**Issue by paulaldridge** [quay/claircore#526]
We've been seeing a lot of panics from the RHEL dockerfile parser which was recently replaced.

For example:
```
panic: runtime error: slice bounds out of range [:-1]

goroutine 86265 [running]:
github.com/quay/claircore/rhel/dockerfile.(*labelParser).Run(0xc00e8efef0, 0x1108f20, 0xc00ecbcab0)
	/build/vendor/github.com/quay/claircore/rhel/dockerfile/dockerfile.go:99 +0xe6a
github.com/quay/claircore/rhel/dockerfile.GetLabels(0x1121130, 0xc00e273140, 0x1108f20, 0xc00ecbcab0, 0x0, 0x0, 0x0)
	/build/vendor/github.com/quay/claircore/rhel/dockerfile/dockerfile.go:26 +0x93
github.com/quay/claircore/rhel.extractBuildNVR(0x1121130, 0xc00e273140, 0xc004c94c60, 0x2d, 0xc00ecbcab0, 0x0, 0x0, 0x0, 0x0, 0xc00e273150, ...)
	/build/vendor/github.com/quay/claircore/rhel/repositoryscanner.go:315 +0x66
github.com/quay/claircore/rhel.(*RepositoryScanner).getCPEsUsingContainerAPI(0xc003600ba0, 0x1121130, 0xc00e273140, 0xc0036008a0, 0xc00e273140, 0xc00804a6d0, 0x0, 0x0, 0x0)
	/build/vendor/github.com/quay/claircore/rhel/repositoryscanner.go:248 +0x14f
github.com/quay/claircore/rhel.(*RepositoryScanner).Scan(0xc003600ba0, 0x1121168, 0xc00e781c20, 0xc0036008a0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/build/vendor/github.com/quay/claircore/rhel/repositoryscanner.go:187 +0xafb
github.com/quay/claircore/internal/indexer/layerscanner.(*result).Do(0xc009767e58, 0x1121168, 0xc0084e6570, 0x7f2db434ef98, 0xc003600ba0, 0xc0036008a0, 0x20, 0x20)
	/build/vendor/github.com/quay/claircore/internal/indexer/layerscanner/layerscanner.go:241 +0x299
github.com/quay/claircore/internal/indexer/layerscanner.(*layerScanner).scanLayer(0xc003457020, 0x11210c0, 0xc0084e6570, 0xc0036008a0, 0x7f2db434ef98, 0xc003600ba0, 0x0, 0x0)
	/build/vendor/github.com/quay/claircore/internal/indexer/layerscanner/layerscanner.go:212 +0x85c
github.com/quay/claircore/internal/indexer/layerscanner.(*layerScanner).Scan.func1.1(0x0, 0x0)
	/build/vendor/github.com/quay/claircore/internal/indexer/layerscanner/layerscanner.go:173 +0x147
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc000c46a80, 0xc0011d5240)
	/build/vendor/golang.org/x/sync/errgroup/errgroup.go:57 +0x59
created by golang.org/x/sync/errgroup.(*Group).Go
	/build/vendor/golang.org/x/sync/errgroup/errgroup.go:54 +0x66
```

I haven't managed to track down an example of a dockerfile that is causing this, which might help us solve this properly, but will share one if I manage to.  
When having a play with the code I seem to be able to trip it up when using a multi line env declaration, so I assume it is something along those lines, e.g. 
```
ENV MY_NAME="John Doe" \
    MY_CAT=fluffy
```
This seems to end up split into 3 'pairs': `MY_NAME="John Doe"`, `\`, and `MY_CAT=fluffy`
Then the parser would panic because the 2nd pair doesn’t contain an equals character. 

I’m working on a fix and submit a PR. I also think it would be a good to add a check for "-1" response before using it as an index anyway, and return an error, so I’ll include that in the PR. That will avoid any panics and hopefully provide a more helpful error in the case where we’ve missed something else.

**Comment by paulaldridge** [comment]
Submitted a PR fix: https://github.com/quay/claircore/pull/527

**Comment by hdonnay** [comment]
Is this different from #512? I saw similar errors before that, but it wasn't because of the issue you describe here.

**Comment by paulaldridge** [comment]
@hdonnay I think based on our convo in the PR the multi line env vars should be covered by the lexers `collectLine` function.

I've updated to v1.1.13 which contains https://github.com/quay/claircore/pull/512, and it helped a lot! But there are still a few of these panics we are seeing still (drastically reduced amount though). I'm not sure what is causing it, but as a next step we could check for -1 value before it is used as an slice index, and log the line that is causing the problem for our investigation?

**Comment by paulaldridge** [comment]
I believe this is exactly the same as before but just sharing fyi, this is what we are seeing currently when running v1.1.13:
```
panic: runtime error: slice bounds out of range [:-1]

goroutine 617664 [running]:
github.com/quay/claircore/rhel/dockerfile.(*labelParser).Run(0xc00b5816e0, 0x1107660, 0xc00ba258c0)
	/build/vendor/github.com/quay/claircore/rhel/dockerfile/dockerfile.go:99 +0xe6a
github.com/quay/claircore/rhel/dockerfile.GetLabels(0x111f830, 0xc012e622a0, 0x1107660, 0xc00ba258c0, 0x0, 0x0, 0x0)
	/build/vendor/github.com/quay/claircore/rhel/dockerfile/dockerfile.go:26 +0x93
github.com/quay/claircore/rhel.extractBuildNVR(0x111f830, 0xc012e622a0, 0xc0082c1980, 0x3f, 0xc00ba258c0, 0x0, 0x0, 0x0, 0x0, 0xc012e622b0, ...)
	/build/vendor/github.com/quay/claircore/rhel/repositoryscanner.go:315 +0x66
github.com/quay/claircore/rhel.(*RepositoryScanner).getCPEsUsingContainerAPI(0xc01623aa80, 0x111f830, 0xc012e622a0, 0xc000294960, 0xc012e622a0, 0xc003c1bc70, 0x0, 0x0, 0x0)
	/build/vendor/github.com/quay/claircore/rhel/repositoryscanner.go:248 +0x14f
github.com/quay/claircore/rhel.(*RepositoryScanner).Scan(0xc01623aa80, 0x111f868, 0xc0006d1a70, 0xc000294960, 0x0, 0x0, 0x0, 0x0, 0x0)
	/build/vendor/github.com/quay/claircore/rhel/repositoryscanner.go:187 +0xafb
github.com/quay/claircore/internal/indexer/layerscanner.(*result).Do(0xc00462de58, 0x111f868, 0xc0006d17d0, 0x7f8a2c34e888, 0xc01623aa80, 0xc000294960, 0x20, 0x20)
	/build/vendor/github.com/quay/claircore/internal/indexer/layerscanner/layerscanner.go:241 +0x299
github.com/quay/claircore/internal/indexer/layerscanner.(*layerScanner).scanLayer(0xc004bcd1a0, 0x111f7c0, 0xc0006d17d0, 0xc000294960, 0x7f8a2c34e888, 0xc01623aa80, 0x0, 0x0)
	/build/vendor/github.com/quay/claircore/internal/indexer/layerscanner/layerscanner.go:212 +0x85c
github.com/quay/claircore/internal/indexer/layerscanner.(*layerScanner).Scan.func1.1(0x0, 0x0)
	/build/vendor/github.com/quay/claircore/internal/indexer/layerscanner/layerscanner.go:173 +0x147
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc03dce13e0, 0xc001dac080)
	/build/vendor/golang.org/x/sync/errgroup/errgroup.go:57 +0x59
created by golang.org/x/sync/errgroup.(*Group).Go
	/build/vendor/golang.org/x/sync/errgroup/errgroup.go:54 +0x66

```

**Comment by hdonnay** [comment]
I'm hesitant to just add a `-1` check because it's a programmer logic error, not an expected value that the code is just failing to handle.

That said, I think I've found the issue. It is indeed a logic error.

**Comment by paulaldridge** [comment]
Nice thanks for looking into it @hdonnay

**Comment by hdonnay** [comment]
Thanks for opening an issue and being patient!

**Comment by paulaldridge** [comment]
@hdonnay that fix did seem to help again and reduced the amount of panics a bit, but unfortuntely we are still seeing the same error as above after updating to v1.1.6 
Sorry I've not got more details on what's causing it but just wanted to let you know

**Comment by hdonnay** [comment]
got another change in #542 -- I stumbled across some comment handling oddities while adding some fuzzing

**Comment by paulaldridge** [comment]
nice find thank you
