### ISSUE TITLE
Index out of range while scanning JAR file 

### ISSUE THREAD

**Issue by ammachado** [quay/claircore#541]
```go
{"level":"warn","component":"java/Scanner.Scan","kind":"package","layer":"sha256:f9c522e94d1ae7331c4dd9833271d30a9e0d468e40c009dd6d6924cf906fbf78","manifest":"sha256:e393b189a2192fe7dcf2d741ce1e878e89fdeaf09254d017f214c0c5f17b84f3","scanner":"java","state":"ScanLayers","version":"3","error":"Get \"https://search.maven.org/solrsearch/select?q=1%3A%22a4a4b7c2225d25c6fdac44e01e90be19bb132922%22&wt=json\": dial tcp 3.213.49.41:443: connect: network is unreachable","time":"2021-12-10T19:58:24Z","message":"error making request"}
panic: runtime error: index out of range [-1]

goroutine 4372 [running]:
archive/zip.split(...)
	/opt/rh/go-toolset-1.16/root/usr/lib/go-toolset-1.16-golang/src/archive/zip/reader.go:751
archive/zip.fileEntryLess(0xc000838d50, 0x30, 0x16b1518, 0x0, 0xf53a01)
	/opt/rh/go-toolset-1.16/root/usr/lib/go-toolset-1.16-golang/src/archive/zip/reader.go:725 +0x255
archive/zip.(*Reader).initFileList.func1.1(0x0, 0xa90, 0x1)
	/opt/rh/go-toolset-1.16/root/usr/lib/go-toolset-1.16-golang/src/archive/zip/reader.go:719 +0x6f
sort.doPivot_func(0xc000702ca0, 0xc00022b9b0, 0x0, 0xa92, 0x0, 0x7f96c419b558)
	/opt/rh/go-toolset-1.16/root/usr/lib/go-toolset-1.16-golang/src/sort/zfuncversion.go:89 +0x424
sort.quickSort_func(0xc000702ca0, 0xc00022b9b0, 0x0, 0xa92, 0x18)
	/opt/rh/go-toolset-1.16/root/usr/lib/go-toolset-1.16-golang/src/sort/zfuncversion.go:143 +0x97
sort.Slice(0xe51980, 0xc0004f86d8, 0xc000702ca0)
	/opt/rh/go-toolset-1.16/root/usr/lib/go-toolset-1.16-golang/src/sort/slice.go:20 +0xe8
archive/zip.(*Reader).initFileList.func1()
	/opt/rh/go-toolset-1.16/root/usr/lib/go-toolset-1.16-golang/src/archive/zip/reader.go:719 +0x5a5
sync.(*Once).doSlow(0xc000246040, 0xc000702f10)
	/opt/rh/go-toolset-1.16/root/usr/lib/go-toolset-1.16-golang/src/sync/once.go:68 +0xec
sync.(*Once).Do(...)
	/opt/rh/go-toolset-1.16/root/usr/lib/go-toolset-1.16-golang/src/sync/once.go:59
archive/zip.(*Reader).initFileList(0xc000246000)
	/opt/rh/go-toolset-1.16/root/usr/lib/go-toolset-1.16-golang/src/archive/zip/reader.go:689 +0x65
archive/zip.(*Reader).Open(0xc000246000, 0xfe78ff, 0x8, 0x0, 0x0, 0x1753e00, 0xc000703030)
	/opt/rh/go-toolset-1.16/root/usr/lib/go-toolset-1.16-golang/src/archive/zip/reader.go:734 +0x2f
io/fs.Stat(0x112d980, 0xc000246000, 0xfe78ff, 0x8, 0x0, 0x0, 0x0, 0x0)
	/opt/rh/go-toolset-1.16/root/usr/lib/go-toolset-1.16-golang/src/io/fs/stat.go:25 +0xa2
io/fs.WalkDir(0x112d980, 0xc000246000, 0xfe78ff, 0x8, 0xc000703130, 0x0, 0x0)
	/opt/rh/go-toolset-1.16/root/usr/lib/go-toolset-1.16-golang/src/io/fs/walk.go:108 +0x56
github.com/quay/claircore/java/jar.extractProperties(0x1146fe8, 0xc00022b8f0, 0xc00080a1ce, 0xd, 0x112d980, 0xc000246000, 0xc00022b8f0, 0x112ddc0, 0xc000032130, 0xc000032130, ...)
	/remote-source/app/vendor/github.com/quay/claircore/java/jar/jar.go:187 +0xd5
github.com/quay/claircore/java/jar.Parse(0x1146fe8, 0xc00022b8f0, 0xc00080a1c0, 0x1b, 0xc000246000, 0x0, 0x18, 0x1, 0x1, 0x0)
	/remote-source/app/vendor/github.com/quay/claircore/java/jar/jar.go:87 +0x396
github.com/quay/claircore/java.(*Scanner).Scan(0xc00009df40, 0x1146fe8, 0xc000688570, 0xc0003e1920, 0x0, 0x0, 0x0, 0x0, 0x0)
	/remote-source/app/vendor/github.com/quay/claircore/java/packagescanner.go:146 +0xc45
github.com/quay/claircore/internal/indexer/layerscanner.(*result).Do(0xc000703e58, 0x1146fe8, 0xc000594d50, 0x7f96c462d3d8, 0xc00009df40, 0xc0003e1920, 0x20, 0x20)
	/remote-source/app/vendor/github.com/quay/claircore/internal/indexer/layerscanner/layerscanner.go:237 +0xa2
github.com/quay/claircore/internal/indexer/layerscanner.(*layerScanner).scanLayer(0xc00043ac00, 0x1146f40, 0xc000594d50, 0xc0003e1920, 0x7f96c462d3d8, 0xc00009df40, 0x0, 0x0)
	/remote-source/app/vendor/github.com/quay/claircore/internal/indexer/layerscanner/layerscanner.go:212 +0x85c
github.com/quay/claircore/internal/indexer/layerscanner.(*layerScanner).Scan.func1.1(0x0, 0x0)
	/remote-source/app/vendor/github.com/quay/claircore/internal/indexer/layerscanner/layerscanner.go:173 +0x147
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc0008284b0, 0xc0000d1080)
	/remote-source/app/vendor/golang.org/x/sync/errgroup/errgroup.go:57 +0x59
created by golang.org/x/sync/errgroup.(*Group).Go
	/remote-source/app/vendor/golang.org/x/sync/errgroup/errgroup.go:54 +0x66
```

**Comment by hdonnay** [comment]
This issue slipped through the cracks; this has been fixed for a while.
